### ISSUE TITLE
Latest develop does not build with openimageio 1.8.17 metadata.remove

### ISSUE THREAD

**Issue by skinkie** [alicevision/AliceVision#909]
```
/home/skinkie/Sources/AliceVision/src/software/pipeline/main_panoramaWarping.cpp:1210:18: error: 'class OpenImageIO_v1_8::ParamValueList' has no member named 'remove'
 1210 |         metadata.remove("Orientation");
      |                  ^~~~~~
/home/skinkie/Sources/AliceVision/src/software/pipeline/main_panoramaWarping.cpp:1211:18: error: 'class OpenImageIO_v1_8::ParamValueList' has no member named 'remove'
 1211 |         metadata.remove("orientation");
      |  
```

**Comment by simogasp** [comment]
Because it now requires 2.2.6.1
https://github.com/alicevision/AliceVision/blob/c9e2b3e57569748b12a3eb0d2d589db186abb214/CMakeLists.txt#L570

**Comment by skinkie** [comment]
@simogasp lets update the INSTALL.md ;-)
