### ISSUE TITLE
2.4.0 field has incomplete type 'struct timeval'

### ISSUE THREAD

**Issue by yurivict** [alicevision/AliceVision#1012]
clang-10 fails to compile on FreeBSD 12.2
```
/usr/ports/graphics/alice-vision/work/AliceVision-2.4.0/src/dependencies/MeshSDFilter/external/OpenMesh/Tools/Utils/Timer.cc:223:18: error: field has incomplete type 'struct timeval'
  struct timeval start_, stop_;
                 ^
/usr/include/unistd.h:487:8: note: forward declaration of 'OpenMesh::Utils::timeval'
struct timeval;                         /* select(2) */
       ^
```

**Comment by yurivict** [comment]
ping
